### ISSUE TITLE
can't edit augmentation table

### ISSUE THREAD

**Issue by layla-jnp** [Huh/PopR_Jasper#19]
Hi Josh!  
Hey - so just trying to work with IPM and seems that the Augmentation table is (all of a sudden) not editable?  I've tried on a couple browsers, on both databases, and tried a reset just in case.  This has been working in the past without any issue - any ideas if something changed?
Thanks,
LN

**Comment by Huh** [comment]
I may have broke it this afternoon.  I will track down the problem and fix
it tonight...I have to coach hockey shortly, but will get to it shortly.
Apologies for the breakdown and thank you for the issue.

**Comment by Huh** [comment]
Hi Layla,

I updated the site and everything appears to be working as expected again.  We did have some git conflicts to resolve between Anna and I, so please let me know if anything seems odd or is not working.  Thanks again for using this tool and providing enough detail for me to quickly find the problem.

I am going to close this issue, but it can be reopened if I missed something.  If you find other problems please try to keep one bug per issue, so we can track everything.

Josh

**Comment by layla-jnp** [comment]
Hey Josh - wow thanks so much!  I saw your message as I was on my way to pick kids UP from hockey practice and then the rest of the night was chaos haha.. Yes- I had a look this morning, everything is awesome and works (as far as I checked!).  
Will do re: the tool, seems like a great place for a changelog! 
Thanks again for your incredibly fast response and for doing this at like, midnight, wow.
layla

**Comment by Huh** [comment]
Yes, a changelog is going to be part of my next iteration of the workflow.  I really should have one now, but sadly do not.  Thanks for the great suggestion.

The two new databases were created by Anna.  She is out of town at the moment, but I will put in an email to try and get an explanation.  I think they were related to how survival was calculated, but am not sure.

My rule of thumb for issues is to make one for each bug or enhancement that you would like to see.  If you want to have a conversation or just have a question then use email.  I think of the issues as a "to do" list more than a place to have conversations in part because this is public and part because I don't want to clog up the to do list with topics that do not require action.

Thanks Layla,

Josh
